/*
 *
 * Contact constants
 *
 */


export const SEND_CONTACT_INFO_REQUEST = 'SEND_CONTACT_INFO_REQUEST';
export const SEND_CONTACT_INFO_SUCCESS = 'SEND_CONTACT_INFO_SUCCESS';
export const SEND_CONTACT_INFO_FAILURE = 'SEND_CONTACT_INFO_FAILURE';
